spring:
  application:
    name: "analytics-dashboard"
  sql:
    init:
      mode: never
  r2dbc:
    username: sa
    password:

app:
  graceQueryTimeout: 300ms
  maxQueryTimeout: 20m
  caching:
    ttl: 120s
    maxSize: 1000
  r2dbc:
    write-url: "r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;ACCESS_MODE_DATA=rw"
    read-url: "r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;ACCESS_MODE_DATA=r"